services:
  - type: web
    name: innovexia-stripe-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false  # Set manually in Render dashboard
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false  # Set manually in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false  # Set manually in Render dashboard (after configuring webhook)
      - key: FIREBASE_PROJECT_ID
        sync: false  # Set manually in Render dashboard
      - key: FIREBASE_PRIVATE_KEY
        sync: false  # Set manually in Render dashboard
      - key: FIREBASE_CLIENT_EMAIL
        sync: false  # Set manually in Render dashboard
    healthCheckPath: /health
